[package]
name = "shikane"
version = "0.1.0"
edition = "2021"

[dependencies]
calloop = "0.10.1"
clap = { version = "3.2.20", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.17"
serde = { version = "1.0.144", features = ["derive"] }
smithay-client-toolkit = { git = "https://github.com/Smithay/client-toolkit", rev = "87424f2cd10d50422d81ee0444e92becb45d43c4" }
thiserror = "1.0.32"
toml = { version = "0.5.9", features = ["preserve_order"] }
wayland-client = { version = "0.30.0-beta.9", features = ["log"] }
wayland-protocols = { version = "0.30.0-beta.9", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.1.0-beta.9", features = ["client"] }
xdg = "2.4.1"

[patch.crates-io]
wayland-client =        { git = "https://github.com/Smithay/wayland-rs", rev = "9dfaf0d99d701c258ba082f79790495a7fb136eb" }
wayland-protocols =     { git = "https://github.com/Smithay/wayland-rs", rev = "9dfaf0d99d701c258ba082f79790495a7fb136eb" }
wayland-protocols-wlr = { git = "https://github.com/Smithay/wayland-rs", rev = "9dfaf0d99d701c258ba082f79790495a7fb136eb" }
# dependencies
wayland-backend =       { git = "https://github.com/Smithay/wayland-rs", rev = "9dfaf0d99d701c258ba082f79790495a7fb136eb" }
wayland-cursor =        { git = "https://github.com/Smithay/wayland-rs", rev = "9dfaf0d99d701c258ba082f79790495a7fb136eb" }
wayland-sys =           { git = "https://github.com/Smithay/wayland-rs", rev = "9dfaf0d99d701c258ba082f79790495a7fb136eb" }
