[package]
name = "shikane"
version = "0.1.0"
edition = "2021"

[dependencies]
calloop = "0.10.1"
clap = { version = "3.2.20", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.17"
serde = { version = "1.0.144", features = ["derive"] }
smithay-client-toolkit = { git = "https://github.com/Smithay/client-toolkit", rev = "1cc11af8538040f46173bf021ac079c342ddeebb" }
thiserror = "1.0.32"
toml = { version = "0.5.9", features = ["preserve_order"] }
wayland-client = { version = "0.30.0-beta.10", features = ["log"] }
wayland-protocols = { version = "0.30.0-beta.10", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.1.0-beta.10", features = ["client"] }
xdg = "2.4.1"