[package]
name = "shikane"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
log = "0.4.17"
wayland-client = "0.30.0-beta.8"
wayland-protocols = { version = "0.30.0-beta.8", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.1.0-beta.8", features = ["client"] }
